[OPENAI_API_KEY]
OPENAI_API_KEY = "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"


